baseurl = "https://kentsommer.github.io/"
languageCode = "en-US"
title = "Kent Sommer"
# Enable comments by entering your Disqus shortname
disqusShortname = "kentsommer"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Kent Sommer"
  description = "Personal Blog that is supposed to be here to help make my life easier..."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  Github        = "kentsommer"
  Email         = "kent.sommer13@gmail.com"
  Twitter       = "kentsommer"
  LinkedIn      = "kentsommer"
  #Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "resume.pdf"
